apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
      
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-container
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "aswin"      #using env is not recommanded.use secrets instead
          volumeMounts:
            - name: db-volume
              mountPath: /data/db

      volumes:
       - name: db-volume
         hostPath:
            path: /home/aswin/Devops-handson/kubernetes/projects/mongo-mongoexpress/mongo-database  #the path where your volume exist
            type: Directory

        