apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
     
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        
        - name: express-container
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "10.152.183.145"			
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value : "root"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "aswin"

Note: for sensitive data use secret instead of ENV
This code is for testing purpose only
             
             
             
             
             
             
  