apiVersion: v1
kind: Pod
metadata:
  name: mypod-with-two-container
spec:
  
  volumes:
    - name: myvolume
      hostPath:
        path: /home/aswin/pod-vol

  containers:
    - name: mynginx-container-1
      image: nginx
      volumeMounts:
        - name: myvolume
          mountPath: "/usr/share/nginx/html"

 
    - name: mynginx-container-2
      image: nginx
      volumeMounts:
        - name: myvolume
          mountPath: "/usr/share/nginx"




