apiVersion: apps/v1
kind: StatefulSet
metadata: 
    name: mysql-deployment-stateful
    labels:
        app: mysql
spec:
    servicename: mysql-h   // name of the headerless service that we created earlier
    replicase: 2
    matchLabels:
        app: mysql
    template:
        metadata:
            name: myapp-pod 
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: mysql
