apiVersion: v1
kind: Pod
metadata: 
  name: my-pod-with-resource-limits
spec:
  containers:
    - name: mywebserver
      image: nginx

      resources:
        requests:
          memory: "60Mi"
          cpu: "250m"
        limits:
          memory: "100Mi"
          cpu: "300m"


  