apiVersion: v1
kind: Pod
metadata: 
  name: my-firstpod-with-affinity
spec:
  affinity:   # For Defining Affinity
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: #Affinity will only check when scheduling
        nodeSelectorTerms:
          - matchExpressions: #Checking match label disk=ssd
            - key: disk
              operator: In
              values:
                - ssd 


  containers:   # Container of the POD
    - name: mywebserver
      image: nginx
  

Note: This pod will only deploy on a node with a node affinity set to disk=ssd

      