apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
 containers:
     - name: webapps
       image: nginx
       livenessProbe:
         httpGet:
          path: /image
          port: 8080
         initialDelaySeconds: 80
         periodSeconds: 1
